services:
  db:
    image: postgres:10.0-alpine
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

  api:
    image: dockersamples/wordsmith-api
    deploy:
      replicas: 5

  web:
    image: dockersamples/wordsmith-web
    ports:
      - "8080:80"
